# Generated by Django 2.0.6 on 2018-06-18 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('many_to_many', '0002_auto_20180618_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='invite_reason',
            field=models.CharField(max_length=64),
        ),
    ]
