# Generated by Django 2.0.6 on 2018-06-21 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0002_auto_20180619_0648'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersonManager',
        ),
    ]
